#pragma once

#define INITIAL_TITLEBAR_HEIGHT 32U

#define INITIAL_WINDOWSIZE_BEGINNER_X 128U
#define INITIAL_WINDOWSIZE_BEGINNER_Y (128U + INITIAL_TITLEBAR_HEIGHT)
#define INITIAL_WINDOWSIZE_EASY_X     256U
#define INITIAL_WINDOWSIZE_EASY_Y     (256U + INITIAL_TITLEBAR_HEIGHT)
#define INITIAL_WINDOWSIZE_MEDIUM_X   480U
#define INITIAL_WINDOWSIZE_MEDIUM_Y   (256U + INITIAL_TITLEBAR_HEIGHT)
#define INITIAL_WINDOWSIZE_HARD_X     768U
#define INITIAL_WINDOWSIZE_HARD_Y     (384 + INITIAL_TITLEBAR_HEIGHT)

#define INITIAL_GAME_WON_WINDOW_SIZE_X 220U
#define INITIAL_GAME_WON_WINDOW_SIZE_Y 220U

#define INITIAL_DIFF_SELECTION_WINDOW_SIZE_X 300U
#define INITIAL_DIFF_SELECTION_WINDOW_SIZE_Y 300U